### ISSUE TITLE
Conditional hexing mode

### ISSUE THREAD

**Issue by KOLANICH** [rhelmot/monkeyhex#3]
```python
HEX_THRESHOLD = 10**17 # since that hex is more succinct
...
if isinstance(x, int):
    if alwaysHex or abs(x) >= __class__.HEX_THRESHOLD:
        return hex(x)
    else:
        return repr(x)
```

**Comment by rhelmot** [comment]
Sounds like a fun idea. I would take a PR for this that considered the following:

- The feature should be off by default
- The global HEX_THRESHOLD should be a module attribute of `monkeyhex`
- The class-level HEX_THRESHOLD should be a private attribute
