### ISSUE TITLE
pprint saferepr

### ISSUE THREAD

**Issue by Inheritor-Vision** [rhelmot/monkeyhex#7]
Hi,

After updating to the last Python version (3.10.1) & installing monkeyhex again, I have this error:

```Python
>>> import monkeyhex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vision/.local/lib/python3.10/site-packages/monkeyhex.py", line 110, in <module>
    old_safe_repr = pprint._safe_repr
AttributeError: module 'pprint' has no attribute '_safe_repr'. Did you mean: 'saferepr'?
```
Simply changing to `saferepr` solve the pb on my side.

**Comment by rhelmot** [comment]
agh... unfortunately that's not a correct fix. The correct fix would be patching `pprint.PrettyPrinter._safe_repr`. One sec, I'll make it happen

**Comment by rhelmot** [comment]
Fixed and released!
